- package_repo: https://aur.archlinux.org/python310.git
  package_name: python310
- package_repo: https://aur.archlinux.org/python311.git
  package_name: python311
- package_repo: https://aur.archlinux.org/python312.git
  package_name: python312
- package_repo: https://aur.archlinux.org/python313.git
  package_name: python313
- package_repo: https://aur.archlinux.org/yay.git
  package_name: yay
- package_repo: https://aur.archlinux.org/claude-code.git
  package_name: claude-code
- package_repo: https://aur.archlinux.org/lsyncd.git
  package_name: lsyncd
- package_repo: https://aur.archlinux.org/mutagen.io-bin.git
  package_name: mutagen.io-bin
- package_repo: https://github.com/tehrengruber/pingvin-share-x-pkg
  package_name: pingvin-share-x
- package_repo: https://github.com/tehrengruber/victoriametrics-pkg
  package_name: victoriametrics
- package_repo: https://github.com/tehrengruber/vmutils-pkg
  package_name: vmutils

