- package_repo: https://aur.archlinux.org/gcc13.git
  package_name: gcc13
  skip_tests: "true"
- package_repo: https://aur.archlinux.org/gcc14.git
  package_name: gcc14
  skip_tests: "true"
- package_repo: https://aur.archlinux.org/python310.git
  package_name: python310
- package_repo: https://aur.archlinux.org/python311.git
  package_name: python311
- package_repo: https://aur.archlinux.org/python312.git
  package_name: python312
- package_repo: https://aur.archlinux.org/python313.git
  package_name: python313
- package_repo: https://aur.archlinux.org/yay.git
  package_name: yay
- package_repo: https://aur.archlinux.org/claude-code.git
  package_name: claude-code
- package_repo: https://github.com/tehrengruber/pingvin-share-x-pkg
  package_name: pingvin-share-x
