name: Build and release packages

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build-all.yml
    secrets: inherit
    with:
      repo_db_name: arch-pre-built
